#!/usr/bin/env python3
"""
God-Tier File Organizer v4 — File Manager Integration Setup
===========================================================

Run this script ONCE to add "Organize Files Here" to your system's file
manager right-click menu.

Supported platforms:
  • Windows  → adds Explorer context-menu entry via the registry (winreg)
  • Linux    → installs a Nautilus / Nemo / Thunar script
  • macOS    → prints Automator Quick Action instructions

Usage:
    python setup_integration.py            # auto-detect OS and install
    python setup_integration.py --remove   # remove the integration
    python setup_integration.py --check    # check if integration is active
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import stat
import sys
from pathlib import Path

# Path to the organizer script (must sit in the same directory as this file)
_HERE = Path(__file__).parent.resolve()
ORGANIZER_SCRIPT = _HERE / "organize_v4.py"

MENU_LABEL = "Organize Files Here (God-Tier)"


# ─── Windows ──────────────────────────────────────────────────────────────────

def _win_reg_key() -> str:
    return r"Directory\Background\shell\GodTierOrganize"


def install_windows() -> None:
    import winreg  # type: ignore  # only available on Windows

    python_exe = sys.executable
    script = str(ORGANIZER_SCRIPT)

    key_path = _win_reg_key()
    cmd_path = key_path + r"\command"
    command = f'"{python_exe}" "{script}" "%V"'

    # Create the parent key with display label
    with winreg.CreateKeyEx(winreg.HKEY_CLASSES_ROOT, key_path, 0,
                             winreg.KEY_WRITE) as hkey:
        winreg.SetValueEx(hkey, "", 0, winreg.REG_SZ, MENU_LABEL)
        winreg.SetValueEx(hkey, "Icon", 0, winreg.REG_SZ, f'"{python_exe}",0')

    # Create the command subkey
    with winreg.CreateKeyEx(winreg.HKEY_CLASSES_ROOT, cmd_path, 0,
                             winreg.KEY_WRITE) as hkey:
        winreg.SetValueEx(hkey, "", 0, winreg.REG_SZ, command)

    print(f"✅ Windows: '{MENU_LABEL}' added to Explorer right-click menu.")
    print("   Right-click inside any folder → you should now see the option.")
    print("   (You may need to restart Explorer: taskkill /f /im explorer.exe && start explorer)")


def remove_windows() -> None:
    import winreg  # type: ignore

    import subprocess  # noqa: S404 — only used for safe registry deletion
    key_path = _win_reg_key()
    try:
        # Delete recursively using reg.exe (handles subkeys automatically)
        result = subprocess.run(
            ["reg", "delete", f"HKCR\\{key_path}", "/f"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print("✅ Windows: context-menu entry removed.")
        else:
            print(f"⚠️  Could not remove registry key: {result.stderr.strip()}")
    except Exception as exc:
        print(f"❌ Error removing Windows integration: {exc}")


def check_windows() -> bool:
    try:
        import winreg  # type: ignore
        winreg.OpenKey(winreg.HKEY_CLASSES_ROOT, _win_reg_key())
        print("✅ Windows integration is ACTIVE.")
        return True
    except (ImportError, OSError):
        print("✗  Windows integration is NOT active.")
        return False


# ─── Linux (Nautilus / Nemo / Thunar) ────────────────────────────────────────

def _linux_script_paths() -> dict[str, Path]:
    home = Path.home()
    return {
        "nautilus": home / ".local" / "share" / "nautilus" / "scripts" / MENU_LABEL,
        "nemo":     home / ".local" / "share" / "nemo" / "scripts" / MENU_LABEL,
        "thunar":   home / ".config" / "Thunar" / "scripts" / MENU_LABEL,
    }


def _linux_script_content() -> str:
    python_exe = shutil.which("python3") or shutil.which("python") or sys.executable
    script = str(ORGANIZER_SCRIPT)
    return (
        "#!/bin/bash\n"
        "# God-Tier File Organizer — Nautilus/Nemo/Thunar script\n"
        "# Auto-generated by setup_integration.py\n"
        "\n"
        "# Detect current folder from environment (Nautilus) or use pwd\n"
        'FOLDER="${NAUTILUS_SCRIPT_CURRENT_URI#file://}"\n'
        'FOLDER="$(python3 -c "import urllib.parse,sys; print(urllib.parse.unquote(sys.argv[1]))" '
        '"$FOLDER" 2>/dev/null || echo "$FOLDER")"\n'
        '[ -z "$FOLDER" ] && FOLDER="$(pwd)"\n'
        "\n"
        f'exec "{python_exe}" "{script}" "$FOLDER"\n'
    )


def install_linux() -> None:
    installed = []
    paths = _linux_script_paths()
    content = _linux_script_content()

    for manager, script_path in paths.items():
        if script_path.parent.exists():
            script_path.parent.mkdir(parents=True, exist_ok=True)
            script_path.write_text(content, encoding="utf-8")
            script_path.chmod(
                script_path.stat().st_mode
                | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
            )
            installed.append(manager)
            print(f"✅ {manager.capitalize()}: script installed → {script_path}")

    if not installed:
        # Create for Nautilus anyway even if it is not running yet
        first = list(paths.values())[0]
        first.parent.mkdir(parents=True, exist_ok=True)
        first.write_text(content, encoding="utf-8")
        first.chmod(first.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print(f"✅ Nautilus script installed (Nautilus not running yet) → {first}")
        installed.append("nautilus")

    print("\nTo use: right-click inside any folder → Scripts → " + MENU_LABEL)
    print("Restart Nautilus if needed:  nautilus -q")


def remove_linux() -> None:
    for manager, script_path in _linux_script_paths().items():
        if script_path.exists():
            script_path.unlink()
            print(f"✅ {manager.capitalize()}: script removed.")
        else:
            print(f"   {manager.capitalize()}: not installed, skipping.")


def check_linux() -> bool:
    active = False
    for manager, script_path in _linux_script_paths().items():
        if script_path.exists():
            print(f"✅ {manager.capitalize()} integration is ACTIVE → {script_path}")
            active = True
        else:
            print(f"✗  {manager.capitalize()} integration is NOT active.")
    return active


# ─── macOS ────────────────────────────────────────────────────────────────────

def install_macos() -> None:
    python_exe = shutil.which("python3") or sys.executable
    script = str(ORGANIZER_SCRIPT)

    print(
        "\nmacOS Finder integration — Automator Quick Action\n"
        "══════════════════════════════════════════════════\n\n"
        "Automator cannot be automated from the command line, so follow\n"
        "these one-time steps (takes ~3 minutes):\n\n"
        "  1. Open Automator (Applications → Automator)\n"
        "  2. Choose  File → New  →  Quick Action\n"
        "  3. Set  'Workflow receives current'  to  folders  in  Finder\n"
        "  4. Search for 'Run Shell Script' and drag it into the workflow\n"
        "  5. Set Shell to /bin/bash, Pass input: as arguments\n"
        "  6. Paste this script:\n\n"
        f'        "{python_exe}" "{script}" "$1"\n\n'
        "  7. Save the Quick Action as  'Organize Files Here'\n"
        "  8. Right-click any folder in Finder → Quick Actions → Organize Files Here\n"
    )


def remove_macos() -> None:
    service_dir = Path.home() / "Library" / "Services"
    service = service_dir / "Organize Files Here.workflow"
    if service.exists():
        shutil.rmtree(service)
        print("✅ macOS Quick Action removed.")
    else:
        print("✗  macOS Quick Action not found.")


def check_macos() -> bool:
    service = Path.home() / "Library" / "Services" / "Organize Files Here.workflow"
    if service.exists():
        print(f"✅ macOS Quick Action is ACTIVE → {service}")
        return True
    print("✗  macOS Quick Action is NOT active (or installed manually).")
    return False


# ─── Dispatch ─────────────────────────────────────────────────────────────────

def _os_name() -> str:
    system = platform.system().lower()
    if system == "windows":
        return "windows"
    if system == "darwin":
        return "macos"
    return "linux"


def main() -> None:
    if not ORGANIZER_SCRIPT.exists():
        print(f"❌ organize_v4.py not found at: {ORGANIZER_SCRIPT}")
        print("   Keep both files in the same directory and re-run.")
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="Install/remove file-manager integration for God-Tier File Organizer v4"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--remove", action="store_true", help="Remove the integration")
    group.add_argument("--check", action="store_true", help="Check whether integration is active")
    args = parser.parse_args()

    os_name = _os_name()
    print(f"Detected OS: {os_name}\n")

    if os_name == "windows":
        if args.remove:
            remove_windows()
        elif args.check:
            check_windows()
        else:
            install_windows()

    elif os_name == "linux":
        if args.remove:
            remove_linux()
        elif args.check:
            check_linux()
        else:
            install_linux()

    elif os_name == "macos":
        if args.remove:
            remove_macos()
        elif args.check:
            check_macos()
        else:
            install_macos()


if __name__ == "__main__":
    main()
